### ISSUE TITLE
Interruption des scripts suite à une erreur liée au sdk

### ISSUE THREAD

**Issue by SimonSAMPERE** [isogeo/migrations-toolbelt#14]
### Descriptions
Les scripts utilisant les méthodes *import_into_other_metadata()* ou *duplicate_into_other_group()* de la classe **MetadataDuplicator** (`isogeo_migrations_toolbelt/duplicate/duplicator.py`)  sont interrompus par l'erreur suivante : 
```
Traceback (most recent call last):
  File "c:/Users/SimonSAMPERE/Documents/GitHub/migrations-toolbelt/scripts/GRDF/try_migrate.py", line 47, in <module>
    associate_catalogs=False,
  File "c:\users\simonsampere\documents\github\migrations-toolbelt\isogeo_migrations_toolbelt\duplicate\duplicator.py", line 786, in import_into_other_metadata
    metadata=md_dst, keyword=keyword, check_exists=1
  File "C:\Users\SimonSAMPERE\Documents\GitHub\migrations-toolbelt\.venv\lib\site-packages\isogeo_pysdk\decorators.py", line 56, in wrapper
    return decorated_func(*args, **kwargs)
  File "C:\Users\SimonSAMPERE\Documents\GitHub\migrations-toolbelt\.venv\lib\site-packages\isogeo_pysdk\api\routes_keyword.py", line 520, in tagging
    req_check = checker.check_api_response(req_keyword_associate)
  File "C:\Users\SimonSAMPERE\Documents\GitHub\migrations-toolbelt\.venv\lib\site-packages\isogeo_pysdk\checker.py", line 127, in check_api_response
    response.json().get("error"),
  File "C:\Users\SimonSAMPERE\Documents\GitHub\migrations-toolbelt\.venv\lib\site-packages\requests\models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Users\SimonSAMPERE\AppData\Local\Programs\Python\Python37-32\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "C:\Users\USERNAME\AppData\Local\Programs\Python\Python37-32\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\SimonSAMPERE\AppData\Local\Programs\Python\Python37-32\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```
 ### Informations complémentaires
Cette erreur ne survient pas au moment du traitement d'une fiche en particulier.
À un moment, L'API renvoie un code d'erreur dont le traitement par le module **[IsogeoChecker](https://github.com/isogeo/isogeo-api-py-minsdk/blob/cf171c1b5eec34d3ad07324ec4c333933cb1521c/isogeo_pysdk/checker.py)** d'[isogeo-pysdk](https://github.com/isogeo/isogeo-api-py-minsdk) entraîne une erreur Python.
Après quelques tests, il s'avère qu'il s'agit d'un code 401 ("Unauthorized "). 

 ### 2 questions : 
* Pourquoi [le traitement de cette réponse](https://github.com/isogeo/isogeo-api-py-minsdk/blob/cf171c1b5eec34d3ad07324ec4c333933cb1521c/isogeo_pysdk/checker.py#L127) de l'API par le module **[IsogeoChecker](https://github.com/isogeo/isogeo-api-py-minsdk/blob/cf171c1b5eec34d3ad07324ec4c333933cb1521c/isogeo_pysdk/checker.py)** d'[isogeo-pysdk](https://github.com/isogeo/isogeo-api-py-minsdk) entraîne-t-il une erreur Python ?
* Pourquoi l'API renvoie-t-elle ce code erreur ?

**Comment by SimonSAMPERE** [comment]
* La première question à donné lieu à un [ticket](https://github.com/isogeo/isogeo-api-py-minsdk/issues/136) dans le dépôt du package [isogeo-pysdk](https://github.com/isogeo/isogeo-api-py-minsdk)

* La seconde question a été élucidée en faisant des tests et en s'intéressant au token obtenu par le client de l'API utilisé dans le script (via `isogeo.connect()`). Ce **token expire** au bout de 399 secondes (et non 3599). Au bout d'un peu moins de 5 minutes, le token est renouvelé. Pendant son renouvellement, les requêtes envoyées à l'API utilisent un token expiré, **d'où le code 401** retourné par l'API.

**Comment by SimonSAMPERE** [comment]
Il est possible d'accéder à la date d'expiration du token obtenu par le client de l'API : 
```
isogeo.token.get("expires_at")
```
Il faudrait donc rajouter au script une pause quelques secondes avant le renouvellement du token.

**Comment by SimonSAMPERE** [comment]
une solution consiste à ajouter ces lignes au début des boucle qui utilisent le client Isogeo dans leurs itérations :
```python
if default_timer() - auth_timer >= 250:
       logger.info("Manually refreshing token")
       isogeo.connect(
              username=environ.get("ISOGEO_USER_NAME"),
              password=environ.get("ISOGEO_USER_PASSWORD"),
       )
       auth_timer = default_timer()
else:
       pass
```
`auth_timer` ayant été préalablement calculé juste après la première authentification à l'API Isogeo (`isogeo.connect(...`)
Ainsi on rafraichit manuellement le token lorsque son expiration approche afin que ça ne soit pas fait automatiquement au cours d'une autre reqête
